# configs
COMBINE_FACE_WEIGHT = 10
COMBINE_FEATURE_WEIGHT = 10
FEATURE_DETECT_MAX_CORNERS = 50
FEATURE_DETECT_QUALITY_LEVEL = 0.1
FEATURE_DETECT_MIN_DISTANCE = 10
FACE_DETECT_REJECT_LEVELS = 1.3
FACE_DETECT_LEVEL_WEIGHTS = 5

HAARCASCADE_PROFILEFACE = 'haarcascade_profileface.xml'
HAARCASCADE_FRONTALFACE = 'haarcascade_frontalface_default.xml'

VIS = False

HORIZONTAL_THRESHOLD = 1.1
PORTRAIT_THRESHOLD = 0.9